version: "3"

services:
  api:
    build:
      context: . #Build Dockerfile 
    container_name: "flask_api"
    ports:
      - 5001:5001
    networks: 
      - my_network
    restart: always
networks:
    my_network:
        external: true    