# Docker compose MongoDB and Mongo-express
version: '3'

services:
  database:
    image: 'mongo'
    container_name: "db_mongo"
    environment:
      - MONGO_INITDB_DATABASE=DPML_db
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - ./init-mongo.js:/docker-entry-point-initdb.d/init-mongo.js:ro
      - mongo-volumn:/data/db
    ports:
      - "27017:27017"
    networks:
      - my_network
    restart: always

  mongo-express:
    image: mongo-express
    container_name: "mongo-exp"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db_mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    depends_on:
      - database
    ports:
      - "8081:8081"
    networks:
      - my_network
    restart: always
volumes:
  mongo-volumn:

networks:
  my_network:
    external: true